### ISSUE TITLE
Consul example

### ISSUE THREAD

**Issue by johnjelinek** [linkerd/linkerd-examples#11]
I configured linkerd with the settings mentioned in the [docs](https://linkerd.io/doc/0.4.0/config/index.html#consul), but how do I do the service discovery part? Do I manually set k/v stuff? Does it rely on DNS (ie: `consul.service.consul` or `mynode.node.dc1.consul`)? It's not entirely clear what I'm supposed to do next after linkerd is running on the host.

**Comment by olix0r** [comment]
thanks @johnjelinek. we could definitely use a good consul example in this repo.  I think your question was answered in slack?  Regardless, let me explain here so in case someone stumbles on this ticket:

Let's say I have a linkerd configuration like the following:
```yaml
namers:
- kind: io.l5d.experimental.consul
  host: 127.0.0.1
  port: 2181

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  baseDtab: |
    /srv        => /io.l5d.consul/dc1;
    /host       => /srv;
    /http/1.1/* => /host;
```

The [_dtab_](https://linkerd.io/doc/dtabs/) is the important part that maps requests onto service discovery.  In this example, a name like `/http/1.1/GET/users` would map onto `/io.l5d.consul/dc1/users`.  The "users" service would then be watched in consul to determine a list of endpoints for load balancing.

We have an open issue regarding [consul enhancements](https://github.com/BuoyantIO/linkerd/issues/230), so please do let us know if you have any thoughts on how to make this feature more useful.  Thanks!
