### ISSUE TITLE
Need dnsPolicy: ClusterFirstWithHostNet when deploying for CNI + zipkin

### ISSUE THREAD

**Issue by turchanov** [linkerd/linkerd-examples#161]
At least for kubernetes 1.7 one has to specifically request `dnsPolicy: ClusterFirstWithHostNet` for linkerd container in deployment config [linkerd-cni.yml](https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/linkerd-cni.yml) if one wants to use zipkin telemetry
```yaml
...
    telemetry:
    - kind: io.l5d.zipkin
      host: zipkin-collector.default.svc.cluster.local
      port: 9410
      sampleRate: 1.0
...
```
Otherwise due to `hostNetwork: true` Pod specifier (for CNI deployment) the `dnsPolicy: default` is applied so that "cluster" addresses (`....svc.cluster.local`) are not resolved because `default` dns policy is to use node's host /etc/resolv.conf which may or may not (as it is in my case) refer to kube-dns for name resolution, at least this kind (the latter) of resolv.conf setup is done by kubeadm. Anyways this clarification must be stated somewhere (https://discourse.linkerd.io/t/flavors-of-kubernetes/53   ?)

P.S. I do not know since what kubernetes version dns policy `ClusterFirstWithHostNet` is available.
