### ISSUE TITLE
[Example] HTTP/HTTPS Proxy to external public websites?

### ISSUE THREAD

**Issue by gabrielcalderon** [linkerd/linkerd-examples#249]
After following the HTTP Proxy, I decided to try creating a proxy to an external website but nothing seems to work...

Example configuration:
```
admin:
  ip: 0.0.0.0
  port: 9990

routers:
- protocol: http
  dtab: /svc/webapp => /$/inet/xip.io/80
  servers:
  - ip: 0.0.0.0
    port: 8080
```

```
http_proxy=http://localhost:8080 curl http://svc/
results in: unable to stablish connection. 
```

I just want to create a simple HTTP proxy on http://localhost/svc to http://xip.io

Could someone provide examples on how to do HTTP/HTTPS proxies to external public websites? For ex: Google.com, Xip.io, Docker.io ?
